name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coveralls

    - name: Run install_sqlite3 script
      run: bash ./django_migrations_auto/test_app/scripts/install_sqlite3.sh

    - name: Run migrations
      run: |
        python manage.py migrate

    - name: Run tests
      run: |
        DJANGO_SETTINGS_MODULE=django_migrations_auto.settings_test coverage run --source='.' manage.py test django_migrations_auto.tests

    - name: Upload coverage to Coveralls
      run: coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}